# Generated by Django 5.1.2 on 2024-10-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('image_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognized_emotions', to='recognition.imagefeed')),
            ],
        ),
    ]
