# Generated by Django 5.1.2 on 2024-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_remove_imagefeed_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imagefeed',
            name='emotion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='DetectedObject',
        ),
    ]
