# Generated by Django 5.1.2 on 2024-11-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_detectedobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefeed',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='imagefeed',
            name='emotion',
        ),
        migrations.CreateModel(
            name='RecognizedEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(null=True)),
                ('emotion', models.CharField(max_length=30, null=True)),
                ('info_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognized_emotions', to='recognition.imagefeed')),
            ],
        ),
        migrations.DeleteModel(
            name='DetectedObject',
        ),
    ]
