# Generated by Django 5.1.2 on 2024-11-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_videofeed_videoemotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofeed',
            name='user',
        ),
        migrations.DeleteModel(
            name='VideoEmotion',
        ),
        migrations.DeleteModel(
            name='VideoFeed',
        ),
    ]
